# Generated by Django 5.2.4 on 2025-08-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_slides'),
    ]

    operations = [
    ]
