# Generated by Django 5.2.4 on 2025-08-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_auto_20250802_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cast', models.TextField()),
                ('trailer', models.URLField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('backdrop', models.ImageField(upload_to='backdrops/')),
            ],
        ),
    ]
